#!/usr/bin/env python
from __future__ import print_function

import os
import sys

if __name__ == '__main__':
    program_exe_path = sys.argv[1]

    from ddtrace import __file__ as root_directory

    root_directory = os.path.dirname(root_directory)
    boot_directory = os.path.join(root_directory, 'bootstrap')

    python_path = boot_directory

    if 'PYTHONPATH' in os.environ:
        path = os.environ['PYTHONPATH'].split(os.path.pathsep)
        if not boot_directory in path:
            python_path = "%s%s%s" % (boot_directory, os.path.pathsep,
                    os.environ['PYTHONPATH'])

    os.environ['PYTHONPATH'] = python_path

    # Find the executable path
    if not os.path.dirname(program_exe_path):
        program_search_path = os.environ.get('PATH', '').split(os.path.pathsep)
        for path in program_search_path:
            path = os.path.join(path, program_exe_path)
            if os.path.exists(path) and os.access(path, os.X_OK):
                program_exe_path = path
                break

    print("argv:", sys.argv)
    print("pythonpath:", os.environ['PYTHONPATH'])
    print("program path:", program_exe_path)

    os.execl(program_exe_path, program_exe_path, *sys.argv[2:])
